### PR TITLE
Update macOS installation method with Homebrew

### PR DESCRIPTION
**Pull request by singularitti**
Fix comment mentioned in https://github.com/lxgw/LxgwWenKai/pull/58#pullrequestreview-888468804

### CODE REVIEW

**Comment by lxgw** [comment]
感谢！

请问可以把[旧字形文楷](https://github.com/lxgw/LxgwWenkaiTC)也提交到 Homebrew 吗？

**Comment by singularitti** [comment]
可以 @lxgw

**Comment by wutea7** [comment]
请问可以把 Mono 也提交上去吗？@singularitti

**Comment by singularitti** [comment]
> 请问可以把 Mono 也提交上去吗？@singularitti

你好，我记得 Mono 字体[已经提交上去了](https://github.com/Homebrew/homebrew-cask-fonts/blob/dd754afae30462d97f5fb7729153eb460b7a6878/Casks/font-lxgw-wenkai.rb#L14-L16)？请问您是安装不成功么？

**Comment by wutea7** [comment]
> 你好，我记得 Mono 字体[已经提交上去了](https://github.com/Homebrew/homebrew-cask-fonts/blob/dd754afae30462d97f5fb7729153eb460b7a6878/Casks/font-lxgw-wenkai.rb#L14-L16)？请问您是安装不成功么？

卸载重新安装后有了，应该是之前不小心在字体册里手动删除了。打扰了不好意思。。

**Comment by singularitti** [comment]
> 感谢！
> 
> 请问可以把[旧字形文楷](https://github.com/lxgw/LxgwWenkaiTC)也提交到 Homebrew 吗？

[Done](https://github.com/Homebrew/homebrew-cask-fonts/pull/6224).

**Comment by singularitti** [comment]
Also added: https://github.com/Homebrew/homebrew-cask-fonts/pull/6225

**Pull request merged**
